In [1]:
import numpy as np


In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[5]

np.int64(16)

In [4]:
arr[2:7] # slicing from index 2 to 7-1

array([13, 14, 15, 16, 17])

In [5]:
arr[2:7:2] # slicing with 2 steps

array([13, 15, 17])

In [6]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [7]:
arr[2,1]

np.int64(14)

In [8]:
slice_arr = arr[2:6,2:4]
slice_arr

array([[15, 16],
       [21, 22],
       [27, 28]])

In [9]:
np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
bool_index = arr % 2 == 0
bool_index

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [11]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])