In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])

arr

array([1, 2, 3, 4])

In [7]:
a = [1,3.14,"Hello"]

In [8]:
np.array(a)

array(['1', '3.14', 'Hello'], dtype='<U32')

In [9]:
lst = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr = np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [22]:
arr = np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
arr = np.ones((5,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
arr = np.linspace(0,1,50)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [40]:
np.random.rand(10) # normal curve 0 to 1

array([0.68321186, 0.56976146, 0.60507439, 0.58942438, 0.9456685 ,
       0.33101718, 0.95508228, 0.85529985, 0.13829205, 0.64133531])

In [38]:
np.random.randn(10) # standardization -3 ro 3

array([ 0.12280386,  1.33046462, -1.44137754,  0.15508338, -1.66646949,
        0.96065627,  0.16065159,  2.21621243,  0.10583937, -0.2943701 ])

In [45]:
np.random.randint(5) # generates random integer between 0 to given range

3

In [46]:
np.random.randint(2,9,5) # generates random integer between the given range upto the given limit

array([4, 7, 2, 3, 5], dtype=int32)

In [49]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr.shape

(3, 3)

In [54]:
arr.size

9

In [55]:
arr.dtype

dtype('int64')

In [56]:
arr.min()

np.int64(1)

In [57]:
arr.max()

np.int64(9)

In [58]:
arr.sum()

np.int64(45)

In [59]:
np.sum(arr, axis=1) # axis == 1 row-wise sum

array([ 6, 15, 24])

In [60]:
np.sum(arr, axis=0) # axis == 0 colums-wise sum

array([12, 15, 18])

In [61]:
arr.mean() # mean

np.float64(5.0)

In [63]:
arr.std() # standard deviation

np.float64(2.581988897471611)

In [64]:
arr.argmax() # index of maximum element

np.int64(8)

In [65]:
arr.argmin() # index of minimum element

np.int64(0)

In [68]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [69]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [71]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [76]:
arr  = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [79]:
arr = arr.reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])