In [1]:
import numpy as np

In [2]:
##Array Operations

In [29]:
arr = np.array([9,2,3,4,5])
brr = np.array([6,7,8,9,10])

In [18]:
sum = arr + brr 
sum

array([ 7,  9, 11, 13, 15])

In [24]:
product = arr * brr
product

array([ 6, 14, 24, 36, 50])

In [32]:
arr // brr

array([1, 0, 0, 0, 0])

In [31]:
arr / brr

array([1.5       , 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [30]:
arr % brr

array([3, 2, 3, 4, 5])

In [33]:
arr + 10

array([19, 12, 13, 14, 15])